//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeApi2.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LykkeApi2.Strings.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already existsRecord already exists.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your app version is not supported anymore. Please update your app from Google Play and continue enjoying the service..
        /// </summary>
        public static string AndroidUpdateNeededMsg {
            get {
                return ResourceManager.GetString("AndroidUpdateNeededMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Not Found.
        /// </summary>
        public static string AssetNotFound {
            get {
                return ResourceManager.GetString("AssetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Pair Not Found.
        /// </summary>
        public static string AssetPairNotFound {
            get {
                return ResourceManager.GetString("AssetPairNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Balance Not Found.
        /// </summary>
        public static string ClientBalanceNotFound {
            get {
                return ResourceManager.GetString("ClientBalanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client with the same email is already registered.
        /// </summary>
        public static string ClientWithEmailIsRegistered {
            get {
                return ResourceManager.GetString("ClientWithEmailIsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version not supported. Please, update..
        /// </summary>
        public static string DefaultUpdateNeededMsg {
            get {
                return ResourceManager.GetString("DefaultUpdateNeededMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not verified.
        /// </summary>
        public static string EmailNotVerified {
            get {
                return ResourceManager.GetString("EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field should not be empty.
        /// </summary>
        public static string FieldShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("FieldShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not valid.
        /// </summary>
        public static string InvalidPropertyValue {
            get {
                return ResourceManager.GetString("InvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is {0}.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is {0}.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Order Not Found.
        /// </summary>
        public static string NoLimitOrder {
            get {
                return ResourceManager.GetString("NoLimitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit History Not Found.
        /// </summary>
        public static string NoLimitsHistory {
            get {
                return ResourceManager.GetString("NoLimitsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Trade History Not Found.
        /// </summary>
        public static string NoLimitTradesHistory {
            get {
                return ResourceManager.GetString("NoLimitTradesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be empty.
        /// </summary>
        public static string NotEmptyField {
            get {
                return ResourceManager.GetString("NotEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough funds.
        /// </summary>
        public static string NotEnoughFunds {
            get {
                return ResourceManager.GetString("NotEnoughFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service temporarily unavailable. Sorry for the inconvenience..
        /// </summary>
        public static string OperationDisabled {
            get {
                return ResourceManager.GetString("OperationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operataion Details Not Found.
        /// </summary>
        public static string OperationsDetailInfoNotFound {
            get {
                return ResourceManager.GetString("OperationsDetailInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the market order for {0} {1} {2} can not be executed..
        /// </summary>
        public static string OrderWasNotPlaced {
            get {
                return ResourceManager.GetString("OrderWasNotPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset &apos;{0}&apos; does not allow use DepositOption.Other.
        /// </summary>
        public static string OtherDepositOptionsNotAllowFormat {
            get {
                return ResourceManager.GetString("OtherDepositOptionsNotAllowFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order amount should be greater than {0} {1}.
        /// </summary>
        public static string PaymentIsLessThanMinLimit {
            get {
                return ResourceManager.GetString("PaymentIsLessThanMinLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has pending disclaimer.
        /// </summary>
        public static string PendingDisclaimer {
            get {
                return ResourceManager.GetString("PendingDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin should contain digits only.
        /// </summary>
        public static string PinShouldContainsDigitsOnly {
            get {
                return ResourceManager.GetString("PinShouldContainsDigitsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethereum contract is not generated.
        /// </summary>
        public static string PleaseCheckDepositScreen {
            get {
                return ResourceManager.GetString("PleaseCheckDepositScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point limit is 4000.
        /// </summary>
        public static string PointsLimit {
            get {
                return ResourceManager.GetString("PointsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your previous transactions are not settled yet, please try again later.
        /// </summary>
        public static string PreviousTransactionsWereNotCompleted {
            get {
                return ResourceManager.GetString("PreviousTransactionsWereNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your order cannot be set. Price deviation is too high..
        /// </summary>
        public static string PriceGapTooHigh {
            get {
                return ResourceManager.GetString("PriceGapTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to accept your purchase request at this time. We will notify you when this temporary restriction has been lifted. Thank you for your understanding..
        /// </summary>
        public static string ProhibitUserFromUSA {
            get {
                return ResourceManager.GetString("ProhibitUserFromUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record does not exists.
        /// </summary>
        public static string RecordNotExists {
            get {
                return ResourceManager.GetString("RecordNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again after {0} second(s).
        /// </summary>
        public static string RetryInSeconds {
            get {
                return ResourceManager.GetString("RetryInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination address is from the same wallet as the source.
        /// </summary>
        public static string SameDestinationAsSource {
            get {
                return ResourceManager.GetString("SameDestinationAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selling.
        /// </summary>
        public static string Selling {
            get {
                return ResourceManager.GetString("Selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should process existing offchain requests.
        /// </summary>
        public static string ShouldProcessExistingOffchainRequests {
            get {
                return ResourceManager.GetString("ShouldProcessExistingOffchainRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Please contact support: support@lykke.com.
        /// </summary>
        public static string SubmitCodeLimitExceed {
            get {
                return ResourceManager.GetString("SubmitCodeLimitExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are experiencing technical problems. Please try again..
        /// </summary>
        public static string TechnicalProblems {
            get {
                return ResourceManager.GetString("TechnicalProblems", resourceCulture);
            }
        }
    }
}
